[package]
name = "ws-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "~1.40", features = ["full"] }
tokio-tungstenite = "~0.24"
futures-util = "~0.3"
tracing = "~0.1"
tracing-subscriber = { version = "~0.3", features = ["env-filter"] }

